# Generated by Django 4.2 on 2025-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabotage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='period',
            field=models.IntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限')], verbose_name='時限'),
        ),
        migrations.AlterField(
            model_name='courseschedule',
            name='weekday',
            field=models.CharField(choices=[('monday', '月曜日'), ('tuesday', '火曜日'), ('wednesday', '水曜日'), ('thursday', '木曜日'), ('friday', '金曜日')], max_length=10, verbose_name='曜日'),
        ),
    ]
